# Change these first
owner: duckyfuz
repo: upptime-checker

sites:
  - name: Portfolio Site
    url: https://www.kenf.dev/
    method: GET
  - name: Resume Hosting
    url: https://resume.kenf.dev/
    method: GET
  - name: Production Site - GT
    url: $GT_PROD_SITE
    method: GET
  - name: Production Site - HL
    url: $HL_PROD_SITE
    method: GET

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kenf.dev
  # cname: demo.upptime.js.org
  # baseUrl: /upptime-checker
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Kenf's Uptime"
  introTitle: "This is a status monitoring site for Kenf's personal Projects - Powered by **[Uptime](https://github.com/upptime/upptime)**"
  introMessage: Real time up date with no server required — just GitHub Actions, Issues, and Pages
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "11 0 * * *"
  responseTime: "11 23 * * *"
  staticSite: "11 1 * * *"
  summary: "11 0 * * *"
  updateTemplate: "11 0 * * *"
  updates: "11 3 * * *"
  uptime: "*/30 * * * *"

assignees:
  - duckyfuz

user-agent: duckyfux
